blank_issues_enabled: false
contact_links:
  - name: Documentação do projeto
    url: https://github.com/TradingRadarPro/trading-radar-pro#readme
    about: Leia as instruções e padrões antes de abrir uma issue.
